[build]
command = "npx prisma generate && npm run build"
publish = "public"                  # Ensure this points to your static files
functions = "netlify/functions"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"   # Redirect to the server function
status = 200
